# configuration for navsat_tranform_node in robot_localization package

frequency: 5

magnetic_declination_radians: 0

yaw_offset: 0

zero_altitude: true

use_odometry_yaw: false

wait_for_datum: false

#datum: [39.326465, -76.621554, 0.0]

publish_filtered_gps: true

broadcast_utm_transform: true
