# configuration for navsat_tranform_node in robot_localization package

magnetic_declination_radians: 0

yaw_offset: 0

zero_altitude: true

use_odometry_yaw: true

wait_for_datum: false

publish_filtered_gps: true

broadcast_utm_transform: false



